version: '3.7'

services:

  python:
    container_name: python-footbot
    build: ./python
    image: python
    tty: true
    depends_on:
      - db

  db:
    container_name: pgsql-footbot
    build: ./pgsql
    image: pgsql
    ports:
      - "5435:5432"
    volumes:
      - ./backup/last/footbot-latest.sql.gz:/docker-entrypoint-initdb.d/footbot-latest.sql.gz  # ./pgsql/init:/docker
      - ./pgsql/pgdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=footbot
      - POSTGRES_USER=footbot
      - POSTGRES_PASSWORD=footbot

  pgbackup:
    container_name: backup-footbot
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - db:db
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=footbot
      - POSTGRES_USER=footbot
      - POSTGRES_PASSWORD=footbot
      - POSTGRES_EXTRA_OPTS=-Z9
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=82